---
title: "Social_SwissgridEnergie_Vis.Rmd"
---

https://www.statworx.com/ch/blog/customizing-time-and-date-scales-in-ggplot2/
http://applied-r.com/r-dates-and-times/
https://stackoverflow.com/questions/22439540/how-to-get-week-numbers-from-dates
https://www.php.net/manual/de/function.strftime.php

```{r setup, include=FALSE}
library(ggplot2)
library(readr)
library(dplyr)
library(statR)

# Number formatting
options(scipen = 1000000)
options(digits = 6)
```


# Data Import

```{r data import}
data <- read_csv("./Social_SwissgridEnergie.csv")

```

## Visualization 1 - Daily volume

```{r visualisation days, fig.height=8, fig.width=24, echo=FALSE}
ggplot(data, aes(x=date, y=value)) + geom_point(color = "#FF6666", alpha = 0.7) +
  geom_path(color = "#FF6666", alpha = 0.7) +
  scale_x_date(date_labels = "%a\n%d. %m", date_breaks = "1 week") +
  labs(title = "Summe endverbrauchte Energie CH",
       caption = "Quelle: Swissgrid",
       x = NULL,
       y = "GWh") +
  theme_stat() +
 scale_x_date(date_breaks = "month")+
 theme(panel.grid.major.x = element_line(linetype = "solid", size = 0.25, color = "grey"),
        axis.text.x = element_text(angle = 90, hjust = 1))+
        #axis.title.x=element_blank(), # no x-axis labels
        #axis.text.x=element_blank(),
        #axis.ticks.x=element_blank()) +
  ggsave("./daily.png", width = 14)
```

## Visualization 2 - Weekly Volume

```{r visualisation weeks, fig.height=8, fig.width=12}
# Data prep
data_wk <- data %>% 
  mutate(week = format(date, '%Y-%V')) %>% # MO - SO
  group_by(week) %>%
  summarise(weekly_total = sum(value)) %>%
  filter(week != "2020-14") # check

ggplot(data_wk, aes(week)) + 
  geom_bar(aes(weight = weekly_total), fill = "#FF6666")+
  labs(title = "Summe endverbrauchte Energie CH",
       caption = "Quelle: Swissgrid",
       x = NULL,
       y = "GWh") +
  theme_stat() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  ggsave("./weekly.png", width = 14)
```

